name: Birthday Reminder

on: 
  workflow_dispatch:
  schedule: 
    - cron: '0 5 * * *'
    # - cron: '50 9 * * *'

jobs:  
  send-reminder:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        index: [0, 1, 2, 3]  # Indices for the arrays
    env:
      DATES: "08-08 06-19 04-16 12-01"  # Space-separated dates
      NAMES: "Katarina Saga Léon Maja"  # Space-separated names

    steps:
      - name: Set today's date
        run: echo "TODAY=$(date +'%m-%d')" >> $GITHUB_ENV
        
      - name: Extract date and name
        run: |
          # Convert space-separated strings to arrays
          IFS=' ' read -r -a dates <<< "${{ env.DATES }}"
          IFS=' ' read -r -a names <<< "${{ env.NAMES }}"
          
          # Get the date and name for the current index
          date=${dates[${{ matrix.index }}]}
          name=${names[${{ matrix.index }}]}
          
          echo "DATE=$date" >> $GITHUB_ENV
          echo "NAME=$name" >> $GITHUB_ENV

      - name: Check if birthday
        run: |
          if [ "${{ env.TODAY }}" == "${{ env.DATE }}" ]; then
            echo "IS_BIRTHDAY=true" >> $GITHUB_ENV
          else
            echo "IS_BIRTHDAY=false" >> $GITHUB_ENV
          fi

      - name: Send birthday reminder
        if: env.IS_BIRTHDAY == 'true'
        uses: cinotify/github-action@main
        with:
          to: 'emmanuel.duchene@gmail.com'
          subject: "GitHub Actions: It's ${{ env.NAME }}'s birthday today"
          body: "<em>Do not forget to congratulate ${{ env.NAME }} today!</em>"
          type: 'text/html'
