name: Birthday Reminder

on: 
  workflow_dispatch:
  schedule: 
    # - cron: '0 5 * * *'
    - cron: '50 9 * * *'

jobs:  
  send-reminder:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        date: ["2024-11-15", "2024-06-19", "2024-04-16"]
        name: ["Katarina", "Saga", "Léon"]
            
    steps:
    - name: Set today's date
      run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    
    - name: Check if birthday
      run: |
          if [ "${{ env.TODAY }}" == "${{ matrix.date }}" ]; then
            echo "IS_BIRTHDAY=true" >> $GITHUB_ENV
            echo "PERSON_NAME=${{ matrix.name }}" >> $GITHUB_ENV
          else
            echo "IS_BIRTHDAY=false" >> $GITHUB_ENV
          fi
      env:
        IS_BIRTHDAY: "false"
   
    - name: Send test birthday reminder     
      uses: cinotify/github-action@main
      if: env.IS_BIRTHDAY == 'true'
      with:
        to: 'emmanuel.duchene@gmail.com'
        subject: "GitHub Actions: It's ${{ env.PERSON_NAME }}'s birthday today"
        body: "<em>Do not forget to congratulate ${{ env.PERSON_NAME}} today!</em>"
        type: 'text/html'      
