name: Context and Variables
env: 
  important: 6
  workflowVariable: "Workflow variable"

on: 
  workflow_dispatch:
    inputs:
      should_fail:
        description: "Fail if < 7"
        required: true
        type: string
        default: "6"

jobs: 
  build-project:
    runs-on: ubuntu-latest
    steps:
    - name: Step that can fail
      run: |
        echo "Failcheck..."
        if (( ${{inputs.should_fail}} < 7 )); then
          exit 1
        fi
    - uses: actions/checkout@v4
    - name : Build solution
      run: dotnet build

    - name: on-failure
      if: ${{ failure() }}
      run: echo "Oops, ${{inputs.should_fail}} was lesser than 7"

    - name: on-success
      if: ${{ success() }}
      run: echo "Success! Input was 7 or more (${{inputs.should_fail}})!"

  print-variables:
    env:
      jobVariable: "Job variable"
    runs-on: ubuntu-latest
    steps:
      
    - name: Print all variables
      env:
        stepVariable: "Step variable"
      run: |
        echo "This is the workflow variable: ${{env.workflowVariable}}
        This is the job variable: ${{env.jobVariable}}
        This is the step variable: ${{env.stepVariable}}"
        
  build-on-different-os:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [8.0, 7.0, 6.0]
    steps:
      - name: Setup .NET
        uses: actions/checkout@v4
        with:
          version: ${{ matrix.version }}
      - run: dotnet build






















    
      
